openapi: 3.0.0
info:
  title: Togather Backend
  version: 1.0.0
servers:
  - url: https://zealous-elk-loafers.cyclic.app/api/v1
paths:
  /users:
    get:
      tags:
        - default
      summary: Get All Users
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Joe
                email: johne3@gmail.com
                mobile: "085123456789"
                userName: joe232345
                address: solo
                age: "30"
                password: password1234
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/3IA4m4rNs3nS2RvDdEvgKpeuYm5ezwvGQrQb:
    get:
      tags:
        - default
      summary: Get Single User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIzSUE0bTRyTnMzblMyUnZEZEV2Z0twZXVZbTVlend2R1FyUWIiLCJpYXQiOjE2Nzg0NzI5OTgsImV4cCI6MTY4MTA2NDk5OH0.VEfFMX8yaXjQew2AZxDKNdX1zJhvNkcizYYdv4RpbrE
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIzSUE0bTRyTnMzblMyUnZEZEV2Z0twZXVZbTVlend2R1FyUWIiLCJpYXQiOjE2Nzg0NzI5OTgsImV4cCI6MTY4MTA2NDk5OH0.VEfFMX8yaXjQew2AZxDKNdX1zJhvNkcizYYdv4RpbrE
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/IblsZer_iBEyyt0CwAz_Kp6-Z7fHx53yUg2w:
    patch:
      tags:
        - default
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                mobile: "085123456780"
                userName: aligator
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/register:
    post:
      tags:
        - default
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Greta
                email: testing2@gmail.com
                mobile: "085123456789"
                userName: testing2
                password: "1234567"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: joe35@gmail.com
                password: password1234
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login/google:
    post:
      tags:
        - default
      summary: Google Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                credential: >-
                  eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1NWNjYTZlYzI4MTA2MDJkODBiZWM4OWU0NTZjNDQ5NWQ3NDE4YmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2Nzg0NzEyMjAsImF1ZCI6IjU2MTI2NjE1NTYwMi1ubzMzazJ0NDJ1NTdtbXVsYWxhcTJzMTFpZGxhbzU3dC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwNTEwOTYzMTU2MzkwNjA0Mjk2NyIsImVtYWlsIjoiYWRpd3NudUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiNTYxMjY2MTU1NjAyLW5vMzNrMnQ0MnU1N21tdWxhbGFxMnMxMWlkbGFvNTd0LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6IkFkaSBXaXNudSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BR05teXhiT2ltZ1dxMXptcFBzaGdlWVF0X0N2cGwwUW9zRXhJbmo2LU1SYj1zOTYtYyIsImdpdmVuX25hbWUiOiJBZGkiLCJmYW1pbHlfbmFtZSI6Ildpc251IiwiaWF0IjoxNjc4NDcxNTIwLCJleHAiOjE2Nzg0NzUxMjAsImp0aSI6IjM2NTg2Y2MwOTU2ZmQyM2MwOTU2NmVhMjZjMTViOGUyZDYxMTZmOWYifQ.QGxnBB9XtZhnHuMQuYO-G2g4az8r8nbfBR9xl9RzjOZ_PT6wsT5C_ViytHFpb5vzxhjed-b1PmXeGjf_J0pOvvl6DA6JZrZHt6JQK0QTW1pHjTTYITzCTy3VIm2ifWA5RBCWmGqYh3gUbixrVf0zptuGDYsyOQQX4ow3LXQFwqgelOecWBNTnFTBVi7Gznh-cPwIYfuGwQtGf6yE1wbIFm3kcuDnO2yqLvZ9nx-TruZwfinYbp5FQFWtc54jIov8bTPE8bF9_E_xrYzpx0K0L9gWsOpYqBvPUnnWCFM3WFyXug87UvGAT8PfIhhDLQUjFcNscFpdGE6c-iweHBzIwQ
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms:
    get:
      tags:
        - default
      summary: Get All Rooms
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms/auth:
    post:
      tags:
        - default
      summary: Create Room
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                roomName: testing status 13
                membersCount: 1
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms/auth/R-0wYjz8BG3JuZsqLrkI9Ng:
    get:
      tags:
        - default
      summary: Get Single Room
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: Edit Room
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                members:
                  - hdbNuN48saKMUdxrkilz2dbyrCBy8IJS8vNT
                  - nd1DQiIE8B1uFEea-oGRDqXI0LfLBW_2lHlW
                  - BNSSivCS7Wb-oHuMoJq0TeDikZP6I2bCWWQW
                  - hdbNuN48saKMUdxrkilz2dbyrCBy8IJS8vNT
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2NzgyNzE5MjMsImV4cCI6MTY4MDg2MzkyM30.AwveLL41ZhfBYsF0RG_D0bhYvLTn1Mkfi1RfgEPR_qc
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms/auth/R-pZSFWmApctn2fFz6r-1Ki:
    delete:
      tags:
        - default
      summary: Delete Room
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJ1bnl2anN3THpwZTVYSXBqd1NGUWZDdnJUeW14eW9ucXpZdWciLCJpYXQiOjE2NzgwODg4NzEsImV4cCI6MTY4MDY4MDg3MX0.kifiE7inevLOPMZ_QVTDfChtlyWxJsCs57tzz48T_Ck
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms/auth/:
    get:
      tags:
        - default
      summary: Get User Created Rooms
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJ1bnl2anN3THpwZTVYSXBqd1NGUWZDdnJUeW14eW9ucXpZdWciLCJpYXQiOjE2Nzc3NDc1MzIsImV4cCI6MTY4MDMzOTUzMn0.EXO6-WbxCzTC6Sz3axQ-bucT4unfrNxYTbT_iINqOG4
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms/auth/R-0wYjz8BG3JuZsqLrkI9Ng/join:
    patch:
      tags:
        - default
      summary: Join room
      requestBody:
        content: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJoZGJOdU40OHNhS01VZHhya2lsejJkYnlyQ0J5OElKUzh2TlQiLCJpYXQiOjE2NzgyNjg5OTYsImV4cCI6MTY4MDg2MDk5Nn0.WLhN7FCqn5rEZhLvT4_OJi3-nvKUxn5Mgs9af6UNRXU
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /rooms/auth/R-x4ktLDr5oJJfQZz6Yt6pL/leave:
    patch:
      tags:
        - default
      summary: Leave Room
      requestBody:
        content: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJoZGJOdU40OHNhS01VZHhya2lsejJkYnlyQ0J5OElKUzh2TlQiLCJpYXQiOjE2NzgyNjg5OTYsImV4cCI6MTY4MDg2MDk5Nn0.WLhN7FCqn5rEZhLvT4_OJi3-nvKUxn5Mgs9af6UNRXU
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops:
    get:
      tags:
        - default
      summary: Get Shops
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Shop
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                shopName: testing shop
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-nJmZCBJVp1gz8dka:
    get:
      tags:
        - default
      summary: Get One Shop
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: Update Shop
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                shopName: testing shop update
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Shop
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces:
    get:
      tags:
        - default
      summary: Get All Spaces
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Space
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                spaceName: testing space 4
                capacity: 5
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces/4526:
    get:
      tags:
        - default
      summary: Get One Space
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces/5565:
    patch:
      tags:
        - default
      summary: Update Space
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Space
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces/4526/booking:
    post:
      tags:
        - default
      summary: Create Booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                roomID: R-vuf3o1gYjfl58AxTHXyGk
                start: "2023-04-01T09:00:00.000Z"
                end: "2023-04-01T11:00:00.000Z"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get Booking
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces/4526/booking/K6TMCMuo/accept:
    patch:
      tags:
        - default
      summary: Accept Booking
      requestBody:
        content: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces/4526/booking/71zDu9Hc/reject:
    patch:
      tags:
        - default
      summary: Reject Booking
      requestBody:
        content:
          "*/*":
            schema:
              type: string
              example: '""'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /shops/S-0Gwm30ioVofMZQI0/spaces/4526/booking/dE-0_cN8:
    delete:
      tags:
        - default
      summary: Delete Booking
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJwN3labnFFWjJwazI4aFRhY0xNaHQ0aVp0RXVTT195NjBSMmsiLCJpYXQiOjE2Nzk0NzAyMjMsImV4cCI6MTY4MjA2MjIyM30.FwHcU2JU0G3z9IOH3Yimsd6G3HHt5KQd3L2vf9kCSqw
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
